name: Comment on the pull request
on:
  workflow_run:
    workflows:
      - ScreenShotTest
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact
        run: echo "download artifact later"
      - name: Comment PR
        run: echo "comment pr later"
